export const ACTIONS = {
    SET_CATEGORIES: 'SET_CATEGORIES',
    ADD_CATEGORY: 'ADD_CATEGORY',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    ADD_ITEM: 'ADD_ITEM',
    SAVE_LIST: 'SAVE_LIST',
    DELETE_ITEM: 'DELETE_ITEM',
    TOGGLE_ITEM_COMPLETION: 'TOGGLE_ITEM_COMPLETION',
    CLEAR_CURRENT_LIST: 'CLEAR_CURRENT_LIST',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    DELETE_CATEGORY: 'DELETE_CATEGORY'  

  };